### ISSUE TITLE
Proper Data is not sent to Sentry

### ISSUE THREAD

**Issue by jdagrawal008** [jmather/SentryForSalesforce#3]
Hi Jacob,

Your code is a little outdated. Lots of essential details which are needed to be sent to Sentry aren't covered in your code. I have updated the code that covers almost all those essential details. I'm not sure how I can contribute to your repo. Please suggest me how we can enhance the existing code.

Regards,
Jheel

**Comment by jmather** [comment]
The simplest way is to fork the repo, make a branch, and push your changes,
but if you're not up for that, you could send me a zip of your copy and I
can make a branch and PR for it to take a look.

**Comment by jdagrawal008** [comment]
@jmather I have just added the pull request for the same. Can you please have a look at it?
