### ISSUE TITLE
Is there a better way to use use this solution?

### ISSUE THREAD

**Issue by 3r1k0n** [jmather/SentryForSalesforce#7]
The suggested usage includes wrapping all code in a try/catch block and calling `Sentry.record(e);` in the handler.

However I feel this can lead to situations where full bodies of most methods will be encapsuled inside try/catch blocks. Not very clean or maintainable.

Is there a better way to handle any unhandled exceptions in Salesforce rather than using try/catch blocks?

**Comment by jmather** [comment]
Not until we have a platform level uncaught exception event, which I believe I *HAVE* heard rumors about.

For triggers though, you could just put the wrapping in the trigger itself... 

```apex
trigger CaseTrigger on Case (before update) {
  try {
     CaseHandler h = new CaseHandler();
     h.run();
   } catch (Exception e) {
    ... record
   }
}
```

or if you have consolidated your handler patterns, you could even just put it in the handler's wrapping code. A more composible form of the prior example for this might look like...

```apex
class TriggerHandler {
  public static void run(ITriggerHandler handler) {
    try {
      handler.run();
    } catch (Exception e) {
      ... record
   }
}

trigger CaseTrigger on Case (before update) {
  TriggerHandler.run(CaseTriggerHandler.class);
}
```

**Comment by 3r1k0n** [comment]
Answered
